<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" type="text/css" href="cssNANA.css">
</head>
<body>
	<h3>Rankings</h3>
	<div>
		<p>Dificuldade Fácil</p>
		<table>
			<tr>
				<th>#</th>
				<th>Nickname</th>
				<th>Id</th>
				<th>Time</th>
				<th>Rounds</th>
			</tr>
			<tr>
				<td>1</td>
				<td>Abelhinha</td>
				<td>4512</td>
				<td>05:12</td>
				<td>12</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Roberson23</td>
				<td>3904</td>
				<td>05:30</td>
				<td>11</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Iceberg</td>
				<td>2112</td>
				<td>05:59</td>
				<td>15</td>
			</tr>
			<tr>
				<td>4</td>
				<td>luaBela01</td>
				<td>5619</td>
				<td>06:10</td>
				<td>14</td>
			</tr>
			<tr>
				<td>5</td>
				<td>20come</td>
				<td>3214</td>
				<td>06:10</td>
				<td>17</td>
			</tr>
		</table>
	</div>
	<br> <br>
	<div>
		<p>Dificuldade Fácil</p>
		<table>
			<tr>
				<th>#</th>
				<th>Nickname</th>
				<th>Id</th>
				<th>Time</th>
				<th>Rounds</th>
			</tr>
			<tr>
				<td>1</td>
				<td>Abelhinha</td>
				<td>4512</td>
				<td>05:12</td>
				<td>12</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Roberson23</td>
				<td>3904</td>
				<td>05:30</td>
				<td>11</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Iceberg</td>
				<td>2112</td>
				<td>05:59</td>
				<td>15</td>
			</tr>
			<tr>
				<td>4</td>
				<td>luaBela01</td>
				<td>5619</td>
				<td>06:10</td>
				<td>14</td>
			</tr>
			<tr>
				<td>5</td>
				<td>20come</td>
				<td>3214</td>
				<td>06:10</td>
				<td>17</td>
			</tr>
		</table>
	</div>
	<br> <br>
	<div>
		<p>Dificuldade Fácil</p>
		<table>
			<tr>
				<th>#</th>
				<th>Nickname</th>
				<th>Id</th>
				<th>Time</th>
				<th>Rounds</th>
			</tr>
			<tr>
				<td>1</td>
				<td>Abelhinha</td>
				<td>4512</td>
				<td>05:12</td>
				<td>12</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Roberson23</td>
				<td>3904</td>
				<td>05:30</td>
				<td>11</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Iceberg</td>
				<td>2112</td>
				<td>05:59</td>
				<td>15</td>
			</tr>
			<tr>
				<td>4</td>
				<td>luaBela01</td>
				<td>5619</td>
				<td>06:10</td>
				<td>14</td>
			</tr>
			<tr>
				<td>5</td>
				<td>20come</td>
				<td>3214</td>
				<td>06:10</td>
				<td>17</td>
			</tr>
		</table>
	</div>
</body>
</html>